// This file was generated by counterfeiter
package fake_namespacer

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/old/rootfs_provider"
)

type FakeNamespacer struct {
	NamespaceStub        func(path string) (string, error)
	namespaceMutex       sync.RWMutex
	namespaceArgsForCall []struct {
		path string
	}
	namespaceReturns struct {
		result1 string
		result2 error
	}
}

func (fake *FakeNamespacer) Namespace(path string) (string, error) {
	fake.namespaceMutex.Lock()
	fake.namespaceArgsForCall = append(fake.namespaceArgsForCall, struct {
		path string
	}{path})
	fake.namespaceMutex.Unlock()
	if fake.NamespaceStub != nil {
		return fake.NamespaceStub(path)
	} else {
		return fake.namespaceReturns.result1, fake.namespaceReturns.result2
	}
}

func (fake *FakeNamespacer) NamespaceCallCount() int {
	fake.namespaceMutex.RLock()
	defer fake.namespaceMutex.RUnlock()
	return len(fake.namespaceArgsForCall)
}

func (fake *FakeNamespacer) NamespaceArgsForCall(i int) string {
	fake.namespaceMutex.RLock()
	defer fake.namespaceMutex.RUnlock()
	return fake.namespaceArgsForCall[i].path
}

func (fake *FakeNamespacer) NamespaceReturns(result1 string, result2 error) {
	fake.NamespaceStub = nil
	fake.namespaceReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ rootfs_provider.Namespacer = new(FakeNamespacer)
