#!/usr/bin/env bash

set -e

ARGS=$@

if egrep -q integration <(echo "$ARGS"); then
  fly -p --exclude-ignored -- -slowSpecThreshold 15 -nodes 1 $ARGS
elif [ -d $ARGS ] && 
     [ "$(find $ARGS -maxdepth 1 -name '*_linux_test.go')" != "" ]; then
  fly -p --exclude-ignored -- -slowSpecThreshold 15 $ARGS
else
  ginkgo -r -race $ARGS
fi

